### ISSUE TITLE
Redes sociais no responsivo

### ISSUE THREAD

**Issue by agnogueira** [CMCuritiba/cmcuritiba.portalmodelo.theme#10]
Os menus de redes sociais não são exibidos no mobile. Poderia aparecer no rodapé talvez, dependendo do modelo que for adotado. Teria que trocar uma ideia sobre isso. Senado Federal exibe só os menus principais (outros acessórios, que não precisa) e redes sociais, tanto no mobile quanto no desktop. Ah, e colocar um voltar ao topo.

**Comment by agnogueira** [comment]
@DePorto Os ícones de redes sociais do topo são escondidos intencionalmente, pois os links para redes sociais já aparecem no rodapé. Quando ajustarmos ficarão mais visíveis acredito. Já é suficiente?

Vou providenciar nesta tarefa apenas link para o topo.

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, acredito que seja suficiente sim. Tem um app desse no Elfsight, que eu comentei contigo - na verdade está ativo no pm3, no final da página inicial. Porém tem que embedar em cada página que quiser que apareça. Mas este é só o link para a rede social mesmo, não é de compartilhamento. É esse código aqui:
<script src="https://apps.elfsight.com/p/platform.js" defer></script>
<div class="elfsight-app-11d47c81-b088-41aa-a068-77d068fa175b"></div>


Link para o topo tem um app também. Mas esse eu posso inserir, mas aí não consigo colocar em todas as páginas, a não ser que seja manualmente. Eis o código do app: <script src="https://apps.elfsight.com/p/platform.js" defer></script>
<div class="elfsight-app-5bbce581-8991-42a7-85c4-f1823b97fda6"></div>


Essa questão dos menus que é citado o site do Senado, me parece que está misturado aqui neste tópico. Vou conferir na lista geral e depois confirmo. Seria sobre o menu no mobile exibir de forma diferente do que está hj, que abre uma lista muito grande e a ideia seria abrir somente os menus principais, sem os submenus aparecendo. Confere aqui: https://www12.senado.leg.br/hpsenado

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 o código é o mesmo nos dois casos, acredito que você configure tudo na página do app.
Vou adicionar de maneira geral ao tema, assim vemos o que acontece e tratamos os casos, ok?

**Comment by agnogueira** [comment]
Itens adicionados
