### ISSUE TITLE
Notícia: ajuste no tamanho da foto

### ISSUE THREAD

**Issue by agnogueira** [CMCuritiba/cmcuritiba.portalmodelo.theme#11]
Temos um problema com a foto. Ela está no tamanho solicitado, mas a imagem não pega a coluna inteira, sobre a uma pequena "faixa" de texto. No entanto, isso é corrigido ao se colocar uma legenda maior sob a foto. Dá para ajustar com a legenda, mas fica meio gambiarra. Então, o ideal seria a foto ficar fixa no tamanho da coluna. As que estão ajustadas, se vc consultar, foi pq houve ajuste na legenda.

**Comment by agnogueira** [comment]
Corrigido pelo commit 
https://github.com/CMCuritiba/cmcuritiba.portalmodelo.theme/commit/2a3691207d78d90a6b746418fbc8cf4a08c7a7b7

**Comment by ramiroluz** [comment]
Talvez não tenha relação, mas para referencia cruzada pois acredito que a solução foi parecida.

https://github.com/CMCuritiba/implantacaoPortalModelo/issues/18
https://github.com/CMCuritiba/implantacaoPortalModelo/issues/19

A solução encontrada foi a customização do template de notícias. Essa customização foi feita manualmente, precisa ser inserida no tema.

/portal_skins/plone_content/newsitem_view/manage_main

Após customizar a página fica em:

/portal_skins/custom/newsitem_view/pt_editForm
