### ISSUE TITLE
Notícias: links de redes sociais

### ISSUE THREAD

**Issue by agnogueira** [CMCuritiba/cmcuritiba.portalmodelo.theme#12]
Os ícones de redes sociais nas notícias não estão alinhados. Sobre isso, Deini, nós estamos assinando um serviço digital com algumas ferramentas, entre elas uma que vai permitir linkar e monitorar os ícones de redes sociais. Está em fase final de contratação, então tem que aguardar uns dias para ver se vai ser compatível.

**Comment by agnogueira** [comment]
Aguardando definições

**Comment by DePorto** [comment]
Bem, se já há um acordo entre você e a Comunicação nesse sentido, a definição fica a cargo de vocês. Estou meio na condição de leva e traz, nesse caso como vocês decidirem, fica a critério. As demandas que sumarizei aqui foram-me repassadas pela Comunicação. Sem problemas.

**Comment by agnogueira** [comment]
@DePorto não temos nenhum acerto não, apenas li a mensagem aí que dizem estar contratando outro solução para isso. Ou entendi errado?

**Comment by agnogueira** [comment]
De qualquer maneira fiz o alinhamento dos ícones disponíveis
https://github.com/CMCuritiba/cmcuritiba.portalmodelo.theme/commit/c9c7f6cee1090920406fbe158a86b954bb0de0b9

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, aqui está o link embed do app que comentei contigo: 

<script src="https://apps.elfsight.com/p/platform.js" defer></script>
<div class="elfsight-app-870b2e69-38cd-4678-aeda-e22d68cf2b54"></div>

Este item de compartilhamento ficaria padrão em todas as notícias. Naquela área que você inseriu os atuais links de compartilhamento.
