### ISSUE TITLE
Incluir frase no final da notícia

### ISSUE THREAD

**Issue by agnogueira** [CMCuritiba/cmcuritiba.portalmodelo.theme#13]
Pedido pro André é que a frase "Reprodução do texto autorizada mediante citação da Câmara Municipal de Curitiba" que utilizamos no final do texto atualmente fique também no final do texto de uma maneira automatizada. Tem como? Para desentupir aquelas informações ali em cima da foto.

**Comment by agnogueira** [comment]
@DePorto Essa frase deve aparecer em todas as páginas? ou apenas nas notícias?

**Comment by DePorto** [comment]
@agnogueira apenas nas notícias

**Comment by agnogueira** [comment]
Frase adicionada antes do rodapé em todas as notícias.

https://github.com/CMCuritiba/cmcuritiba.portalmodelo.theme/commit/67a7b65557a46699329eb666acc3696e3db787ed

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, esta melhoria foi implementada? Pq no pm3 ainda não está visível.

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 apliquei no ambiente de vocês hoje

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, visualizei a aplicação.

Mas preciso que você faça dois ajustes.

1 - Que a frase apareça em negrito e itálico.

 **_» Reprodução do texto autorizada mediante citação da Câmara Municipal de Curitiba._** 

2 - Que a frase apareça um parágrafo abaixo do texto da notícia e antes das tags. Motivo: no mobile, a "assinatura" fica depois dos portlets, como último conteúdo a ser exibido, muito descolada do texto.

Como está nesta notícia aqui: https://pm3.cmc.pr.gov.br/informacao/noticias/camara-lamenta-a-morte-do-ex-vereador-flavio-da-costa

Obrigado.

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 alteração feita.
