### ISSUE TITLE
Notícia: problema na legenda de imagens secundárias

### ISSUE THREAD

**Issue by agnogueira** [CMCuritiba/cmcuritiba.portalmodelo.theme#14]
Quando publico fotos nas notícias, além da foto principal, em tamanhos reduzidos, a legenda não fica alinhada com a imagem. Vou enviar duas imagens nos anexos. Está aqui neste link: https://pm3.cmc.pr.gov.br/informacao/noticias/proposta-mudanca-na-divisa-entre-curitiba-e-sao-jose-dos-pinhais

**Comment by agnogueira** [comment]
Corrigido pelo commit 
https://github.com/CMCuritiba/cmcuritiba.portalmodelo.theme/commit/2fbaf9670ed97c8740195ecec50121349afcdf1b

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, ficou certinho. Porém, tem como colocar aquela mesma opção que tem na imagem principal, um link Voltar para o site, senão o usuário fica sem opção, a não ser clicar em voltar no seu navegador. O ideal, aliás, seria Voltar para a notícia. Mas se der pelo menos para repetir o Voltar para o site já está bom.

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 não seria melhor remover esse link? Acho que não faz muito sentido ampliar essas imagens.

**Comment by MarcioSilvaCMC2020** [comment]
Então @agnogueira, o problema é que, se ficar como está, a pessoa não consegue baixar a foto em uma resolução melhor, somente neste formato de miniatura mesmo. E muitas pessoas (veículos de imprensa principalmente) baixam estas imagens para publicar. Assim, fica inviável se ficar neste formato miniatura.

**Comment by agnogueira** [comment]
Entendi @MarcioSilvaCMC2020
Esse é um recurso padrão do Plone. Para alterar esse funcionamento, precisa alterar o template padrão para as notícias do Plone, foge um pouco do escopo do tema. Acho que o ideal seria consultar o pessoal do desenvolvimento da Câmara.

**Comment by MarcioSilvaCMC2020** [comment]
Certo, @agnogueira. Uma outra questão. Seria possível criar um padrão de imagem de 300 pixels? Explico: nesta medida de 300px, a imagem preenche uma coluna. O que não ocorre neste tamanho padrão de 200px. Já no de 400px, estoura a coluna e desarranja o layout. Pq neste formato padrão, na verdade ele comporta a imagem no tamanho (200 ou 400) e cria um link para a abrir a imagem no tamanho original. Portanto, um padrão de 300px seria o ideal para nós. Caso não seja possível, vamos deixar tudo como está e nos virar....

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 é possivel sim, essa configuração fica em https://pm3.cmc.pr.gov.br/@@imaging-controlpanel (precisa perfil de administrador do portal.

Criei um tamanho novo lá, chamado Intermediário, com 300px

Veja por favor se isso atende

**Comment by MarcioSilvaCMC2020** [comment]
Oi, @agnogueira. Então, funcionou até que bem esse tamanho, mas ainda não é o ideal. Vou colocar o print aqui. Mas preciso de uma ajuda sua. Eu queria o melhor tamanho para "fechar" em uma coluna. Em 300 ainda sobre um tamanho lateral. Eu fiz alguns testes e em 350 eu sei que estoura a coluna. Porém entre 300 e 350 ele deu resultados diferentes em celulares (tamanhos de telas diferentes). A pergunta é: existe um tamanho (entre 300 e 350) que fosse o ideia para preencher uma coluna e pudéssemos aplicar?

![image](https://user-images.githubusercontent.com/67330940/89206423-ab590900-d58f-11ea-9d4e-c07424b4da5a.png)

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 O melhor nesses casos é utilizar um tamanho um pouco maior, como 400px. Mesmo que a imagem seja maior que a largura da tela no responsivo, a imagem vai se adequar

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, então, estava testando aqui. A verdade é que ele tem o tamanho de 400px já, que ele chama de preview, mas não sei o porquê, ele estou o layout com essa medida??? Pode verificar aqui, na segunda imagem, no responsivo. Ele não ajusta automaticamente....

https://pm3.cmc.pr.gov.br/informacao/noticias/proposta-mudanca-na-divisa-entre-curitiba-e-sao-jose-dos-pinhais

![image](https://user-images.githubusercontent.com/67330940/89309583-f3d4fd00-d649-11ea-9e3e-c23d5d1f8dcc.png)

 Pode ver como ele corta o texto e a imagem... ;-(

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 o problema parece de algum outro elemento que esta maior do que deveria, aí a imagem segue este tamanho. Fiz um ajuste aqui, ja deve estar corrigido agora. Verifique novamente por favor

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, está funcionando ok. Obrigado.

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, não sei o que aconteceu, mas a imagem de 400px deixou de funcionar como estava. Não está atendendo ao responsivo.
Consegue verificar, por favor?
Está aqui: https://pm3.cmc.pr.gov.br/informacao/noticias/proposta-mudanca-na-divisa-entre-curitiba-e-sao-jose-dos-pinhais

![image](https://user-images.githubusercontent.com/67330940/89971498-bec04000-dc31-11ea-9b33-493133fceafb.png)

![image](https://user-images.githubusercontent.com/67330940/89971508-c54eb780-dc31-11ea-8a8c-a0bc20197772.png)

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, no item notícia as imagens em tamanhos maiores de 400px, seja o large, ou o original (que antes ele ajustava), não estão funcionando também no modo responsivo, mesmo que eu coloque em linha, que seria centralizado. Peço a gentileza de verificar que todos os tamanhos de imagens funcionem no responsivo, principalmente 400px e, se possível, se for maior que a página - que deve ser uns 800px - que ajuste automático. Ou pelo menos o large.

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 O problema apareceu depois que passaram a inserir a legenda da foto.
O estilo foi corrigido, agora funciona normalmente das duas maneiras

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, infelizmente não funcionou aqui pra mim ;(

Somente o intermediário (300px), os tamanhos maiores (400 ou large) ele estoura o layout....
Pior que descobri que telas maiores o tamanho é 414px e daí quebra o texto....
Não tem como deixar de um jeito que ajuste automaticamente para as telas mobile?

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 sim, já esta dessa maneira. A imagem pode ser maior, mas nunca vai ter mais do que 100% da tela.
Tente atualizar a página aí, provavelmente você não esta com os estilos atualizados, como aconteceu na issue do menu

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira creio ter idenfitificado o problema...a Foto de 400px está ok agora. Funciona com a legenda. Porém, em fotos maiores, seja no tamanho large - ou maior ainda (original) - apesar de estar ajustando, NÃO está funcionando ao ativar a legenda da foto. Aí tenho que fazer a legenda manualmente, o que é ruim para nós. Tem como fazer essa correção? Obrigado.

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 pode deixar um exemplo deste caso disponivel para que eu possa visualizar?

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira 

Aqui neste link: https://pm3.cmc.pr.gov.br/informacao/noticias/a-camara-municipal-no-tempo-dos-imperadores

Vamos lá...

Foto 400px com legenda - Ok, funcionando.
Foto 2 - (com essa legenda Panorâmica de Curitiba em 1870. Cenário ainda rural no período do Brasil Império. (Foto – Acervo Casa da Memória) eu usei a função legenda - então ele NÂO ajustou a foto - mas não estourou o layout. Porém cortou a foto na lateral E a legenda no mobile.

Publiquei a mesma foto logo abaixo SEM a opção legenda e ela fez o ajuste, sem cortar a foto.

Depois publiquei a foto com os índios SEM legenda e ajustou e funcionou blz.
Depois publique COM legenda e estourou o layout.
Conclusão, o problema está na opção legenda.

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 Acho que agora consegui resolver, veja por favor se esta ok.
Aparentemente todos os casos aplicados estão funcionando normalmente agora.

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, bom dia ;)

As fotos estão funcionando. Obrigado.

Porém, restaram 2 probleminhas referentes a esta última alteração. Nas páginas de Notícias, ficou um espaço branco embaixo do rodapé sobrando.  

![image](https://user-images.githubusercontent.com/67330940/91315763-75720380-e78e-11ea-8426-4795fbf1f0c4.png)

Já na seção Arquivo de Notícias (menu Informação) - https://pm3.cmc.pr.gov.br/informacao/historia-das-noticias-cmc/noticias-de-2020

Ainda ficou "sobrando" aquele espaço na lateral:

![image](https://user-images.githubusercontent.com/67330940/91315995-b702ae80-e78e-11ea-83e9-d7883942bf51.png)

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 largura do arquivo corrigida.

Não consegui reproduzir aqui o problema do rodapé. É em algum item específico?

**Comment by MarcioSilvaCMC2020** [comment]
Está funcionando @agnogueira.

**Comment by MarcioSilvaCMC2020** [comment]
Pode fechar a issue. Obrigado.
