### ISSUE TITLE
Tamanho do titulo da coleção de notícias

### ISSUE THREAD

**Issue by agnogueira** [CMCuritiba/cmcuritiba.portalmodelo.theme#15]
Surgiu um bug aqui no tile de coleção de notícias, mais especificamente no cabeçalho. O tamanho do cabeçalho não está ajustando. Mais detalhes no vídeo.
Se possível for, "descolar" um pouco o título do tile da primeira notícia, seria bacana.

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 consegue detalhar um pouco mais esse problema?

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, só para facilitar o histórico, te detalhei esta questão por meio de vídeo enviado no Telegram.

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 os titulos dentro deste tile estão definidos da seguinte maneira:

h2: 1.75em
h3: 1.1em
h4: 1.0em

EM é uma medida de referencia, tem como base a altura de uma fonte básica do corpo do texto.

Como gostaria de fazer a diferenciação dos Hs?
Aumento um pouco o h3?

**Comment by MarcioSilvaCMC2020** [comment]
[Tamanho dos hs_André.pdf](https://github.com/CMCuritiba/cmcuritiba.portalmodelo.theme/files/4973841/Tamanho.dos.hs_Andre.pdf)

@agnogueira , fiz uma comparação entre os padrões de títulos do tiles de embed e de coleção. E os dois têm problemas. Favor conferir no arquivo pdf anexo.

Porém, tentando responder a sua pergunta...
****
Não sei qual o tamanho dos textos dos tiles de embed, mas acredito que se seguirmos essas características, estaremos em bons termos. Ou seja, **deixar padronizado com o tile de embed**. Apesar que o h4 não aparece, ainda que seja o menor.

E, **SIM**, tem que ter uma diferença maior entre o h3 e o h4, senão não faz sentido ter mais um tamanho. E olha que eu uso o h4 para os títulos das notícias que estão dentro dos tiles. Apesar que não sei se possuem valores diferentes. Mas o fato é que o h4 tem que ser maior que o título das matérias contidas nos tiles.

Outra coisa, é que o tile de embed centraliza o título e o de coleção alinha à esquerda. Mas não tenho certeza sobre alguma mudança aqui. Acho melhor deixar como está.

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 fiz alguns ajustes e montei uma página para você validar:

https://pm3.cmc.pr.gov.br/teste-de-titulos/

Com relação ao H4 do tile de embed, este é um problema do complemento de capa, não temos como alterar pelo tema

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, em relação aos tamanhos estou de acordo.
Sobre o h4 do tile de embed, td ok.
Tenho duas observações. Uma em relação ao espaçamento entre as linhas, que demonstro no arquivo anexo;
e outra em relação ao espaço entre o título da coleção de notícias e as notícias em si, que também demonstro em arquivo anexo.
Peço a gentileza de verificar e ver se é possível ajustar.

[Títulos e espaçamento para André.pdf](https://github.com/CMCuritiba/cmcuritiba.portalmodelo.theme/files/4985609/Titulos.e.espacamento.para.Andre.pdf)

[Espaço título e coleção.pdf](https://github.com/CMCuritiba/cmcuritiba.portalmodelo.theme/files/4985611/Espaco.titulo.e.colecao.pdf)

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 ajustes feitos. você pode verificar na capa de teste: https://pm3.cmc.pr.gov.br/teste-de-titulos/

**Comment by MarcioSilvaCMC2020** [comment]
Muito bom, @agnogueira.
