### ISSUE TITLE
Tile de embed não responsivo

### ISSUE THREAD

**Issue by MarcioSilvaCMC2020** [CMCuritiba/cmcuritiba.portalmodelo.theme#16]
OI, @agnogueira. Olha, só, sinceramente não sei se é um problema do site ou do app que gera o slider. Eu até mandei um e-mail para eles (Elsight) e aguardo resposta. Porém, já peço a sua ajuda para você verificar se é possível ajustar alguma coisa no site. O fato é que eu embedo o slider e ele até funcionaria perfeitamente bem para o desktop, porém quebra tudo no responsivo, não funciona e na capa bagunça todo o resto do conteúdo. Tem um na capa, na segunda coluna do lado direito e outro nesta página que eu coloquei só de teste, mas o resultado foi o mesmo: https://pm3.cmc.pr.gov.br/institucional/fale-com-a-camara/fale-com-a-camara/
Na capa, com este ajuste que está ele funcionou bem, em uma coluna (formato vertical). Consegue dar uma olhada nisso?

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 aqui me parece que os embeds estão responsivos, reduzindo a largura no celular.
Consegue me mandar o print do que esta quebrado aí para você?

**Comment by MarcioSilvaCMC2020** [comment]
Oi, @agnogueira. Então, não é nenhum problema no site não. Consegui resolver com a empresa responsável. Era um problema de layout da ferramenta deles.
