### ISSUE TITLE
Frase de assinatura das notícias no formulário da Ouvidoria

### ISSUE THREAD

**Issue by MarcioSilvaCMC2020** [CMCuritiba/cmcuritiba.portalmodelo.theme#17]
Oi, @agnogueira. Não sei por qual motivo, aquela frase que inserimos na assinatura das notícias:

Reprodução do texto autorizada mediante citação da Câmara Municipal de Curitiba 

Está aparecendo em algumas páginas. Mas devem aparecer somente no item Notícia.

Por exemplo, aqui: https://pm3.cmc.pr.gov.br/transparencia/perguntas-frequentes-faq

E, mais importante, na página de formulário da ouvidoria:

https://pm3.cmc.pr.gov.br/ouvidoria

Tem como acertar isso? Para que fique somente nas páginas de notícias mesmo.

![image](https://user-images.githubusercontent.com/67330940/87438162-922eef00-c5c5-11ea-8b81-9146a843e2ca.png)

![image](https://user-images.githubusercontent.com/67330940/87438195-9d821a80-c5c5-11ea-9e8e-01f13200fd1b.png)

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 corrigido, agora realmente aparece apenas em notícias. Veja se esta ok para você

**Comment by MarcioSilvaCMC2020** [comment]
Sim, está ok @agnogueira. Obrigado.
