### ISSUE TITLE
Menu superior Contato

### ISSUE THREAD

**Issue by MarcioSilvaCMC2020** [CMCuritiba/cmcuritiba.portalmodelo.theme#18]
@agnogueira, tem um link de Contato entre aqueles links que estão no topo do portal, ele abre um mini formulário com o seguinte texto:

Formulário de contato
Portal institucional da Câmara Municipal de Curitiba.
Preencha este formulário para entrar em contato com a administração do site.

Ocorre que há um menu logo abaixo Entre em contato, com link para uma página com diversos meios de contato com a CMC. Assim sendo, entendo ser necessário suprimir o link que está mais ao topo do site, pq pode gerar uma confusão na forma de a pessoa entrar em contato com a CMC. Além disso, eu nem sei para onde vai esse contato com a "administração do site".

![image](https://user-images.githubusercontent.com/67330940/87564571-efdf3c00-c696-11ea-8bee-6ca79fd062d6.png)

![image](https://user-images.githubusercontent.com/67330940/87564589-f40b5980-c696-11ea-939e-2e496c54f93b.png)

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 link alterado.

Apenas para ficar registrado, esse link é uma das ações padrão do Plone, caso alguem de TI precise ajustar em algum momento
https://pm3.cmc.pr.gov.br/portal_actions/site_actions/contact

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, eu estava conferindo o site no modo responsivo e inserir a página neste local (menu superior contato) funciona ok no desktop, mas no mobile fica bem desconfigurado. Uma pergunta. Tem como não abrir nada neste link Contato, mas redirecionar para a página Entre em contato? Aí não teríamos esse problema de responsividade. Obrigado.

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 não entendi. Pelo que vi aqui os dois links apontam para a mesma página
https://pm3.cmc.pr.gov.br/institucional/fale-com-a-camara

Ou você está falando de alguma outra?

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, ele abre o link certo, porém ele abre como se fosse em um pop-up e não na página de destino em si. Creio eu que ele abre no espaço que havia para o formulário. Parece que ele não abre no formato de um link externo.

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 Entendi. é uma configuração do Plone que busca abrir formularios simples em popup.
Desabilitei essa opção

**Comment by MarcioSilvaCMC2020** [comment]
Perfeito, @agnogueira.
