### ISSUE TITLE
Ajustar layout php -> Portal Modelo Plone.

### ISSUE THREAD

**Issue by ramiroluz** [CMCuritiba/cmcuritiba.portalmodelo.theme#19]
Precisamos que essa lista siga os estilos do tema do plone, assim, se mudar o tema, muda junto a lista.

https://tmp.curitiba.pr.leg.br/institucional/historia-das-noticias-cmc/noticias-do-legislativo

Esse script mostra a lista e resultados da pesquisa e do filtro por ano:
https://www.curitiba.pr.leg.br/ass.limpo.php

Depois essa url vai mudar de servidor ou nome apenas:

https://outro_nome.curitiba.pr.leg.br/ass.limpo.php

**Comment by ramiroluz** [comment]
@agnogueira se puder ajudar com a parte visual desse script, eu posso fazer os ajustes no php. É um repositório fechado, tem que ver como faz para que outros possam contribuir.

**Comment by agnogueira** [comment]
> Precisamos que essa lista siga os estilos do tema do plone, assim, se mudar o tema, muda junto a lista.
> https://tmp.curitiba.pr.leg.br/institucional/historia-das-noticias-cmc/noticias-do-legislativo

@ramiroluz Não consegui acessar este endereço.


> Esse script mostra a lista e resultados da pesquisa e do filtro por ano:
> https://www.curitiba.pr.leg.br/ass.limpo.php

Como vai ser a apresentação final dele? Vai ser inserido no miolo das paginas do portal? ou vai ser isolado mesmo sem cabeçalho?

**Comment by ramiroluz** [comment]
É um iframe para: www.cmc.pr.gov.br/ass_limpo.php

No pm3 que você deve ter acesso, tem uma pasta que ainda não foi publicada, contendo as noticias embutidas.

**Comment by agnogueira** [comment]
Certo, então devo apenas cuidar das fontes e posicionamento das imagens? Certo @ramiroluz ?

**Comment by ramiroluz** [comment]
Isso gostariamos de sugestão de css adequado por exemplo. Já tá razoável, mas se ficar padronizado com o conteúdo do plone fica mais legal. Se quiser sugerir um html para a navegação, a gente pode implementar no php, temos total acesso e liberdade. Eu não estou gostando do form/lista/detalhe e voltar. Mas estou sem cabeça para pensar em algo razoável.

Vai ser embutido num iframe. https://pm3.cmc.pr.gov.br/institucional/historia-das-noticias-cmc/

Está privado, então precisa de usuário e senha.
