### ISSUE TITLE
Incompatibilidade Googe Chrome

### ISSUE THREAD

**Issue by MarcioSilvaCMC2020** [CMCuritiba/cmcuritiba.portalmodelo.theme#20]
Oi, @agnogueira. Duas questões em relação a incompatibilidades que percebi ao acessar o site por meio do Google Chrome - as quais não ocorrem no Mozilla Firefox. Vamos a elas:

1 - Slider de notícias corta, na parte inferior, as bolinhas que mostram a evolução das notícias.

2 - Os títulos das notícias, nos tiles ao lado (que é uma lista de itens) aparecem em tamanho maior que no Firefox, o que acaba por desconfigurar um pouco o layout desejado.

![image](https://user-images.githubusercontent.com/67330940/87959800-d28ce200-ca89-11ea-8b1e-a8d880f84969.png)

![image](https://user-images.githubusercontent.com/67330940/87959855-e20c2b00-ca89-11ea-8086-447b0a578f77.png)

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 aqui para mim não esta ocorrendo o problema. ELe ainda segue acontecendo para você? Consegue testar em um chrome de outro computador?

**Comment by MarcioSilvaCMC2020** [comment]
Oi, @agnogueira. Descobri o que aconteceu. O Chrome estava configurado com fonte grande e não na média, que é o recomendado. Mas enfim, continua sendo um problema, não? Pq se não estiver na configuração "padrão" vai dar uma bagunçada...Mas perguntei para outras pessoas e estava normal. Acredito que seja a configuração padrão e que a maioria das pessoas não altera. O que vc acha?

**Comment by agnogueira** [comment]
Era o que eu estava imaginando mesmo. O restante dos textos me parecia maior tambem.
Não temos muito controle sobre isso, que utiliza este recurso esta acostumado com uma certa bagunça com relação a isso
