### ISSUE TITLE
Logo do Interlegis na aba do navegador

### ISSUE THREAD

**Issue by MarcioSilvaCMC2020** [CMCuritiba/cmcuritiba.portalmodelo.theme#21]
@agnogueira, as abas dos navegadores de internet ainda mostram a logo do Interlegis - e não a da CMC. Tem como resolver isso? Valeu ;-)

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 corrigido, talvez precise recarregar bastante a página aí para fazer efeito

**Comment by MarcioSilvaCMC2020** [comment]
Perfeito, @agnogueira.
