### ISSUE TITLE
Instalação do widget VLibras

### ISSUE THREAD

**Issue by MarcioSilvaCMC2020** [CMCuritiba/cmcuritiba.portalmodelo.theme#22]
@agnogueira, é possível instalar o widget do Vlibras em todo o nosso site? A ferramenta é gratuita e eles disponibilizam o código aqui neste link:

https://www.vlibras.gov.br/doc/widget/installation/webpageintegration.html

Eu queria ver como funcionaria na página.

Valeu!

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 widget adicionado, veja se está ok

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, está ok. Estamos vendo a contratação de um app semelhante, porém mais completo. Mas não deve estar disponível antes do lançamento do site. Minha única preocupação é saber o caminho para fazer essa alteração depois.
