### ISSUE TITLE
Problemas gerais

### ISSUE THREAD

**Issue by MarcioSilvaCMC2020** [CMCuritiba/cmcuritiba.portalmodelo.theme#23]
@agnogueira, não sei o que aconteceu, se foi uma incompatibilidade com algo adicionado ao site, mas algumas ferramentas que estavam funcionando bem, começaram a apresentar problemas. Reparei agora de manhã:

- [ ] Botão voltar ao topo desapareceu das notícias (no mobile).

- [ ] Menu sanduíche da capa não está funcionando (**APENAS** quando estou logado)

- [ ] No mobile, fundo da capa ficou azul, mesma cor do rodapé.

- [ ] Acredito que em função do item anterior, desabilitou links da capa e de outras páginas (no mobile), que também ficaram com fundo azul.

- [ ] Quando entra na função layout da página aparece tudo desordenado (não sei se pode ser alguma coisa com o servidor)

- [ ] Tile de slider na capa está desconfigurado e uma imagem aparece em cima da outra (desktop). (QUANDO estou logado APENAS)

- [ ] Tile de slider na capa está desconfigurado e uma imagem aparece em cima da outra (desktop).

Consegue verificar essas coisas pra mim? Obrigado.

![image](https://user-images.githubusercontent.com/67330940/89459649-5e1b9980-d73f-11ea-98ad-1dd661690af3.png)

![image](https://user-images.githubusercontent.com/67330940/89459692-712e6980-d73f-11ea-8191-5877b20291f7.png)

**Comment by ramiroluz** [comment]
Fui verificar os problemas e dois deles não ocorreram para mim no navegador Firefox com modo responsivo 320x480.

Testei também no celular, acontece que demorou para carregar alguma coisa, após algum tempo ficou em cache e mais rápido. Mas também não consegui identificar esses dois problemas.

O Sanduíche aparentemente funcionou. O botão voltar ao topo também.

**Comment by ramiroluz** [comment]
O problema do slider da capa, aconteceu comigo apenas quando estou logado (desktop).

**Comment by ramiroluz** [comment]
Reparei que o menu sanduiche não funciona se estiver logado.

**Comment by MarcioSilvaCMC2020** [comment]
Então, @ramiroluz, para mim todos os problemas continuam, o que me impossibilita em subir conteúdos no portal.

**Comment by ramiroluz** [comment]
Tenta acessar https://pm3.curitiba.pr.leg.br/folder_contents dá para quebrar um galho eu acho.

Isso vale para qualquer pasta. 

https://pm3.curitiba.pr.leg.br/institucional/folder_contents
https://pm3.curitiba.pr.leg.br/informacao/noticias/folder_contents

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 acho que eu que tinha criado o problema num dos ultimos ajustes. Refiz o ajuste e as coisas voltaram a funcionar, verifique por favor se esta ok para voces

**Comment by MarcioSilvaCMC2020** [comment]
OI, @agnogueira. Sim, voltou tudo a funcionar. Fechou.
