### ISSUE TITLE
Tile de lista

### ISSUE THREAD

**Issue by MarcioSilvaCMC2020** [CMCuritiba/cmcuritiba.portalmodelo.theme#24]
@agnogueira, tem como fazer um ajuste nesse tile de lista, para que o link que vai embaixo fique alinhado à direita (tenha como limite os outros itens do tile) e não sobrando como ele fica atualmente? Conforme identifiquei no anexo. Obrigado.

[Tile de lista.pdf](https://github.com/CMCuritiba/cmcuritiba.portalmodelo.theme/files/5051527/Tile.de.lista.pdf)

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 alteração feita

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, show de bola.
