### ISSUE TITLE
Tile de carrossel

### ISSUE THREAD

**Issue by MarcioSilvaCMC2020** [CMCuritiba/cmcuritiba.portalmodelo.theme#25]
@agnogueira, sei que você já ajustou alguma coisa nesse tile de carrossel e ele está funcionando. Porém, os ajustes possíveis dentro do tile, na função layout, especialmente tamanho de fonte, não permite nenhuma variação - como aquelas que você ajustou nos tiles de coleção. Minha pergunta é se é possível arrumar esses ajustes, principalmente porque o tamanho do título acaba ficando igual (parece até um pouco menor) que o do tile de lista, que fica ao lado, e as notícias do carrossel precisam ter um destaque um pouco maior. Lembro que você comentou sobre problemas da capa, mas não me recordo se isso limitaria tais ajustes. Ocorre que o tile acaba ficando bem limitado, pq se eu não usar no tamanho que está hoje, com seis colunas e esse tamanho, ele começa a apresentar falhas, o que restringe muito suas funcionalidades. Por exemplo, se um dia quisermos colocar uma notícia no carrossel com destaque maior, mais "estourada", provavelmente não vai funcionar bem. 

Comentário no pdf anexo.

[Tile de carrossel.pdf](https://github.com/CMCuritiba/cmcuritiba.portalmodelo.theme/files/5051643/Tile.de.carrossel.pdf)

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 o controle manual é um pouco limitado nessa versão do tile.
Mas podemos deixar as coisas arrumadas. 
Aumentei um pouco a fonte da aplicação pequena, para ficar um pouco maior do que o tile de lista, mas sem criar uma linha a mais no título.
Aumentei mais um pouco a fonte apenas no caso de aplicação do tile em 8 colunas. 
Veja se isso já ajuda

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 Não tenho como corrigir isso no tema. Esse problema é um dos que citei no início do projeto, que foram corrigidos nas versões mais recentes da ferramenta de capa. Esse tile inclusive foi substituído completamente nessa nova versão.

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, beleza. As alterações que vc fez já ajudaram sim na capa atual. Nas 8 colunas não funciona direito mesmo, corta e fica ruim no responsivo. Mas se está fora da alçada, fica para a próxima tecnologia...
