### ISSUE TITLE
Edição coleção de notícias - Últimas notícias

### ISSUE THREAD

**Issue by MarcioSilvaCMC2020** [CMCuritiba/cmcuritiba.portalmodelo.theme#26]
@agnogueira, veja se consegue me ajudar com isso:

Será possível reduzir as informações exibidas nesta página aqui:

https://pm3.cmc.pr.gov.br/informacao/noticias/ultimas-noticias/

 **CMC aprova prorrogação de alvará a atividades afetadas por pandemia**
— por Fernanda Foggiato — última modificação 10/08/2020 18h05
Leia mais… 

Se for possível, exibir apenas título e data (— última modificação 10/08/2020 18h05), sem o Leia mais....
Deixei uma demonstração em anexo tbm.
Obrigado.

[Ajuste últimas notícias.pdf](https://github.com/CMCuritiba/cmcuritiba.portalmodelo.theme/files/5060364/Ajuste.ultimas.noticias.pdf)

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 escondi os elementos pelo css.
Essa parte do plone é bem ruim, não deixa muito espaço para alterar muito esses elementos pelo tema. Por isso ficaram os dois traços antes da data.
Para remover esses traços, e fazer alguma mudificação um pouco maior, precisa de um pouco de desenvolvimento
