### ISSUE TITLE
Instalação Rybená widget

### ISSUE THREAD

**Issue by MarcioSilvaCMC2020** [CMCuritiba/cmcuritiba.portalmodelo.theme#27]
Bom dia, @agnogueira.
Precisamos fazer um teste com um widget de acessibilidade, que se chama Rybená.
Ele faz, além da leitura do texto em LIBRAS, a leitura de texto em áudio.

[Manual_de_implantacao_Rybena_WEB_Full_v-2.0.pdf](https://github.com/CMCuritiba/cmcuritiba.portalmodelo.theme/files/5069675/Manual_de_implantacao_Rybena_WEB_Full_v-2.0.pdf)

Tem um arquivo Java que não consigo subir por aqui. Acho que foi lá pelo Telegram.

Não é gratuito e ainda não foi adquirido. É para um teste mesmo. Temos 7 dias para testar.
Acho que daria para desabilitar o Vlibras e habilitar esse Rybená.
Caso funcione legal, vamos proceder a compra.
Obrigado!

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 widget adicionado

**Comment by MarcioSilvaCMC2020** [comment]
Obrigado, @agnogueira. Ele abre, mas não consegue ler o nosso texto...Fala para selecionar o texto a ser sintetizado, mas não faz a leitura. Pq será? Obrigado.

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 não consegui ajustar nada aqui nao.
O que faço, removo?

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, pode remover sim, por favor.
Faremos uma apresentação à Mesa Diretora da Câmara na próxima segunda.
Poderia **reinstalar** o VLibras por gentileza.

**Comment by MarcioSilvaCMC2020** [comment]
Caso vc não tenha salvo aí @agnogueira 

https://www.vlibras.gov.br/doc/widget/installation/webpageintegration.html

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 reinstalado
