### ISSUE TITLE
Ajuste no rodapé

### ISSUE THREAD

**Issue by MarcioSilvaCMC2020** [CMCuritiba/cmcuritiba.portalmodelo.theme#28]
@agnogueira, recebi uma demanda do meu chefe para deixar o rodapé, a última parte mesmo, com logo Interlegis e do CC, um pouco mais discreto.

Eu fiz uma sugestão de ajuste e vou anexar aqui.

A ideia é que fique mais discreto e em uma coluna só.

Veja se é possível, por gentileza.

Obrigado ;-)

[Modelo rodapé site CMC.pdf](https://github.com/CMCuritiba/cmcuritiba.portalmodelo.theme/files/5075334/Modelo.rodape.site.CMC.pdf)

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 layout do rodapé alterado
