### ISSUE TITLE
Exibição dos links

### ISSUE THREAD

**Issue by MarcioSilvaCMC2020** [CMCuritiba/cmcuritiba.portalmodelo.theme#29]
@agnogueira, o padrão do site para exibir links está um pouco estranho. Quando inserimos um link no texto, é imperceptível. 

Nos textos do site, quando passo o mouse em um link, ele fica azul. E, depois que eu clico, fica num outro tom de azul.

O ideal, porém, é que o link ficasse azul antes mesmo de ser clicado ou ter que passar o mouse, para facilitar a visualização de que ali é um link por parte do usuário. Parece que ele fica azul mais escuro quando passa o mouse em cima e já foi clicado.

**O **ideal** então seria, um tom de azul mais claro padrão em todos os links e ficar azul mais escuro ao passar o mouse sobre este link.**

Valeu.

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 alteração feita
