### ISSUE TITLE
Ajuste no cabeçalho - MENU

### ISSUE THREAD

**Issue by MarcioSilvaCMC2020** [CMCuritiba/cmcuritiba.portalmodelo.theme#30]
@agnogueira, em conversas com a equipe aqui, consideramos importante colocar junto ao ícone de menu (sanduíche) a palavra Menu, para garantir a visualização por todos os usuários, especialmente os mais idosos.

Eu fiz um esboço de como poderia ficar, mas claro que o ajuste fino tem que ser por aí. Coloquei o arquivo aqui no pdf anexo.
Acredito que diminuindo um pouco o ícone, há espaço para os textos ficarem na mesma proporção. Mas veja o que é possível fazer. Obrigado. 

[Cabeçalho com Menu.pdf](https://github.com/CMCuritiba/cmcuritiba.portalmodelo.theme/files/5096770/Cabecalho.com.Menu.pdf)

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 feito, veja se esta ok

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, a palavra Menu ficou "encavalada" com as outras. Acredito que teria que diminui um pouco o tamanho do ícone (sanduíche) para caber tudo ali em cima e ficar tudo alinhado => Menu Entre em contato | Portal da Transparência

Menu pode ser em caixa baixa mesmo, ok? E as fontes do mesmo tamanho.

Obrigado.

![image](https://user-images.githubusercontent.com/67330940/90670493-a6e84d80-e229-11ea-9401-52d5acf75977.png)

**Comment by agnogueira** [comment]
@agnogueira alterado para texto padrão. Com relação ao estilo, tente recarregar a página, existe um estilo já aplicado que aparentemente não esta carregado para você

**Comment by MarcioSilvaCMC2020** [comment]
Legal @agnogueira

Uma pergunta e uma questão...

A pergunta: no mobile não vai aparecer a expressão menu, certo? Entendo **não** ser necessário.

A questão: tem como retirar essa função de, quando passa o mouse no ícone e palavra Menu, **não** ficar nessa cor cinza/branco?  Não precisa ter nenhuma ação ao passar ao mouse - eu acredito.

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 Sim, ele já não aparece no mobile.
Removida a mudança de cor
