### ISSUE TITLE
Página de Acessibilidade

### ISSUE THREAD

**Issue by MarcioSilvaCMC2020** [CMCuritiba/cmcuritiba.portalmodelo.theme#31]
@agnogueira, conforme minha demanda de editar a página de Acessibilidade - e sua recomendação de criar uma nova página e te passar o link, segue o novo link:

https://pm3.cmc.pr.gov.br/acessibilidade/

Lembrando que esta nova página deve ser a resposta do link Acessibilidade que existe no topo do portal.

Pergunta... Tem como replicar estes comandos de aumentar o texto na nova página?
Que estão aqui:

Tamanho do texto
    Grande
    Normal
    Pequeno

Essa parte queria manter. Eu copiei e colei, mas não veio o comando. Se não der, não tem problema...

Obrigado!

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, outra coisa seria em relação às teclas de acesso - navegação por meio do teclado. Apenas um dos atalhos não está funcionando, que o ALT+9 (ou as outras combinações). Sendo que esse atalho deveria levar para a nossa página de contato (Fale com a Câmara). Tem como acertar isso?

    tecla ALT para os navegadores Microsoft Edge, Google Chrome e Safari.
    teclas SHIFT e ALT, simultaneamente, para o navegador Mozilla Firefox.
    tecla COMMAND para o sistema operacional Mac OS.

Para acessar os itens abaixo, mantenha as teclas pressionadas mais o número escolhido:

    tecla 1 - Página inicial do Portal (no Mozilla Firefox o usuário é levado ao link principal do cabeçalho e precisa pressionar a tecla Enter para ir à página inicial).
    tecla 2 - Conteúdo principal da página
    tecla 3 - Mapa do Site
    tecla 4 - Campo de busca geral
    tecla 5 - Busca Avançada
    tecla 6 — Navegação da sessão corrente do Portal, se houver
    **tecla 9 — Informações de contato**
    tecla 0 -  Página de Acessibilidade

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira esse ALT 6 tbm não funciona, mas eu nem sei o que seria essa tal Navegação.

No site da Câmara dos Deputados diz que é navegação de sessão corrente e fala em (se houver)

tecla 6 — Navegação da sessão corrente do Portal, se houver

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 link alterado.
