### ISSUE TITLE
Exclusão de tags

### ISSUE THREAD

**Issue by MarcioSilvaCMC2020** [CMCuritiba/cmcuritiba.portalmodelo.theme#32]
@agnogueira, preciso de uma ajuda... Você sabe me dizer como eu posso excluir tags que eu criei? Utilizamos as tags para organizar conteúdos, especialmente as notícias. Ocorre que, eventualmente, podemos criar tags duplicadas, enfim, fazer alguma coisa errada. E eu ainda não descobri como excluir. Sei que não é uma questão do tema, só um pedido de ajuda mesmo. Obrigado.

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 existe uma ferramenta de gestão de tags. Ela permite visualizar todas e fazer a gestão, mesclando, apagando ou renomeando. Não é padrão, precisa ser adicionada ao portal pelo pessoal do desenvolvimento.
