### ISSUE TITLE
Alteração Logo nova

### ISSUE THREAD

**Issue by diemello** [CMCuritiba/cmcuritiba.portalmodelo.theme#34]
Alteração da logo para nova enviada pela Diretoria de Comunicação.

Texto novo: Câmara de Curitiba
Fonte: Montserrat black

Modelo da nova logo:
![e10080ec-973a-4875-b6fd-c1ae57e46dca](https://github.com/CMCuritiba/cmcuritiba.portalmodelo.theme/assets/18293096/c3c6748c-b0ad-4ce3-a3ee-70b840e8739b)

**Comment by diemello** [comment]
Conforme reunião, levantados os arquivos necessários para alterações em: https://www.curitiba.pr.leg.br/++theme++tema-camara-municipal-de-curitiba-nova-logo/@@theming-controlpanel-mapper?

**Comment by ramiroluz** [comment]
Existe uma pasta onde são feitas alterações em arquivos processados pelo webpack.

https://github.com/CMCuritiba/cmcuritiba.portalmodelo.theme/tree/master/webpack/app

Eles geram os arquivos na pasta do plone para o tema.

https://github.com/CMCuritiba/cmcuritiba.portalmodelo.theme/tree/master/src/cmcuritiba/portalmodelo/theme/cmcuritiba

O jeito que devemos aplicar as mudanças no código é através do webpack.
