### ISSUE TITLE
Lista de pendências / ajustes para o tema:

### ISSUE THREAD

**Issue by DePorto** [CMCuritiba/cmcuritiba.portalmodelo.theme#4]
- [x] 1. Na capa, falta ajustar o layout do cabeçalho. Eu até havia mandado uma imagem para o André já faz um um bom tempo, mas vamos mandar uma imagem atualizada. Refiro-me aqui somente ao logo da CMC.

- [x] 2. Tem que ajustar os dois menus no cabeçalho:
Entre em contato - não responde nada
Portal da Transparência  - não está com o link

- [x] 3. Tem o rodapé, que está em tabela, e o André disse que não vai funcionar assim. Ele perguntou se poderia resolver e eu já disse que sim, apesar de não saber como. Detalhe, está ativo no desktop, mas não no mobile. Aí eu não sei exatamento como vai resolver. Se ele mantiver essa padrão no desktop está bom. Agora, no mobile, tem que achar um modelo.

- [ ] 4. Tem também aquela questão dos menus "sanduíche". Se para o mobile não poderia seguir o modelo do menu da Câmara dos Deputados, por exemplo. Para não ficar tão longa a lista, nem quebrar a rolagem horizontal - como ocorre hoje.

- [x] 5. Os menus de redes sociais não são exibidos no mobile. Poderia aparecer no rodapé talvez, dependendo do modelo que for adotado. Teria que trocar uma ideia sobre isso. Senado Federal exibe só os menus principais (outros acessórios, que não precisa) e redes sociais, tanto no mobile quanto no desktop. Ah, e colocar um voltar ao topo.

### PÁGINA DE NOTÍCIAS

- [x] 1. Temos um problema com a foto. Ela está no tamanho solicitado, mas a imagem não pega a coluna inteira, sobrea uma pequena "faixa" de texto. No entanto, isso é corrigido ao se colocar uma legenda maior sob a foto. Dá para ajustar com a legenda, mas fica meio gambiarra. Então, o ideal seria a foto ficar fixa no tamanho da coluna. As que estão ajustadas, se vc consultar, foi pq houve ajuste na legenda.

- [x] 2. Os ícones de redes sociais nas notícias não estão alinhados. Sobre isso, Deini, nós estamos assinando um serviço digital com algumas ferramentas, entre elas uma que vai permitir linkar e monitorar os ícones de redes sociais. Está em fase final de contratação, então tem que aguardar uns dias para ver se vai ser compatível.

- [x] 3.  Pedido pro André é que a frase
_"Reprodução do texto autorizada mediante citação da Câmara Municipal de Curitiba"_
que utilizamos no final do texto atualmente fique também no final do texto de uma maneira automatizada. Tem como? Para desentupir aquelas informações ali em cima da foto.

- [x] 4. Quando publico fotos nas notícias, além da foto principal, em tamanhos reduzidos, a legenda não fica alinhada com a imagem. Vou enviar duas imagens nos anexos. Está aqui neste link: https://pm3.cmc.pr.gov.br/informacao/noticias/proposta-mudanca-na-divisa-entre-curitiba-e-sao-jose-dos-pinhais

- [ ] 5. Surgiu um bug aqui no tile de coleção de notícias, mais especificamente no cabeçalho. O tamanho do cabeçalho não está ajustando. Mais detalhes no vídeo.
Se possível for, "descolar" um pouco o título do tile da primeira notícia, seria bacana.

**Comment by DePorto** [comment]
- [x] Outro ponto seria substituir a logomarca atual do site, por esta abaixo:
Aqui está o link: https://drive.google.com/open?id=1FxPMqaXklLO--5fODvxlLLriCNGaq0lS
Sendo preciso redimensionar o tamanho dessa nova imagem para ficar na mesma proporção da atual. E também retirar o texto "Câmara Municipal de Curitiba" que ficaria repetido.

**Comment by agnogueira** [comment]
@DePorto vou quebrar as tarefas em tarefas menores, assim fica mais fácil ir fechando e comentando em pontos específicos. Esta aqui fica só pra referencia.

**Comment by agnogueira** [comment]
Vou fechar esta daqui, todas as tarefas que faltam já possuem tarefas específicas
