### ISSUE TITLE
Redes sociais e alinhamento nas notícias

### ISSUE THREAD

**Issue by DePorto** [CMCuritiba/cmcuritiba.portalmodelo.theme#5]
![redes_sociais](https://user-images.githubusercontent.com/20687716/85310556-80f13780-b48a-11ea-871a-3be075a8eafe.png)

- [x] é possível alinhar corretamente os botões de compartilhamento das redes sociais (que aparecem desalinhados como no exemplo da imagem acima)?

- [x] é possível acrescentar outras redes?

**Comment by agnogueira** [comment]
Itens alinhados.
É possível, as redes estão disponíveis na configuração do social like

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, agora não me lembro se já tinha pedido isso pra vc. Se eu coloquei em outro tópico, me perdoe. Mas, agora que estamos com os links de compartilhamento das redes sociais ativos, vc pode desabilitar esses links antigos que vc mencionou acima: "as redes estão disponíveis na configuração do social like".

**Comment by agnogueira** [comment]
Removido.
As configurações que falei ficam aqui:
https://pm3.cmc.pr.gov.br/@@sociallike-settings

**Comment by MarcioSilvaCMC2020** [comment]
![image](https://user-images.githubusercontent.com/67330940/87315519-f042d000-c4fa-11ea-82e5-32549f0a11cc.png)

Ok, @agnogueira. Só pra constar, não tenho acesso a este link, conforme a imagem anexa.
