### ISSUE TITLE
Alterar logo

### ISSUE THREAD

**Issue by agnogueira** [CMCuritiba/cmcuritiba.portalmodelo.theme#6]
Na capa, falta ajustar o layout do cabeçalho. Eu até havia mandado uma imagem para o André já faz um um bom tempo, mas vamos mandar uma imagem atualizada. Refiro-me aqui somente ao logo da CMC.

**Comment by agnogueira** [comment]
@DePorto vou restaurar aqui o recurso de edição do logo do portal modelo.
Assim vocês poderão altera-lo pelo painel de controle

**Comment by agnogueira** [comment]
Corrigido no commit 
https://github.com/CMCuritiba/cmcuritiba.portalmodelo.theme/commit/157bd6eda01ba22025153d561daaab8f0b2b1611

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, uma pergunta....para além do brasão da CMC (já consigo alterar), aquele texto (que está como link) Câmara Municipal de Curitiba, está no campo Header background image ? Além disso, quais seriam as medidas ideais de tamanho 9em pixels) para estes itens?

![image834](https://user-images.githubusercontent.com/67330940/85641572-56a7a180-b665-11ea-9392-ba5260af8614.png)

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 os textos não estão disponíveis, o texto camara municipal de curitiba esta fixo.

A definição da imagem no CSS está com 87px de largura máximo, a altura fica proporcional

**Comment by MarcioSilvaCMC2020** [comment]
Certo, @agnogueira. Então, eu preciso alterar esse texto/imagem. Vamos manter o brasão ali e adequar a imagem/texto ao lado. Eu mando pra ti, só preciso saber o tamanho da imagem, pq não consigo baixar aqui para ter uma ideia....

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 a altura da imagem é de 87 pixels, a largura pode variar um pouco que vai se adaptar.
Com relação ao texto, basta me enviar que altero aqui

**Comment by MarcioSilvaCMC2020** [comment]
![brasão home-02](https://user-images.githubusercontent.com/67330940/87683432-752a2580-c757-11ea-9f70-f336da831ef2.png)

@agnogueira, consegue publicar esta imagem ao lado do brasão para eu ver como fica? Obrigado.

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 dependendo das fontes que estiverem utilizando, posso alterar o estilo diretamente no Portal, assim não precisamos usar imagem para isso. Consegue me passar que fonte é esta?

**Comment by MarcioSilvaCMC2020** [comment]
Oi, @agnogueira. Utilizamos a fonte Raleway. Só estou vendo aqui as diferenças de estilo entre as duas linhas do texto.

**Comment by MarcioSilvaCMC2020** [comment]
Então, @agnogueira...confirmando: fonte Raleway. Frase de cima na especificação Regular e frase de baixo em Bold.

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 corrigido, veja se esta ok para vocês

**Comment by MarcioSilvaCMC2020** [comment]
Sim, está ok @agnogueira. Só tenho uma dúvida...se for preciso alterar isso posteriomente, nós saberemos fazer isso? Tem como deixar um link, ou mini-tutorial sobre como alterar.

**Comment by agnogueira** [comment]
Marcio,

O texto fica no tema. Optei por fazer assim, pois o campo utilizado pelo portal modelo para isso pede um texto mais longo, que é utilizado em outros locais do site.

O texto fica no tema, especificamente nesta linha:
https://github.com/CMCuritiba/cmcuritiba.portalmodelo.theme/blob/master/webpack/app/index.html#L44

Da maneira como o tema está instalado hoje, também é possível altera-lo pela gestão do tema, acessando o tema ativo e editando o arquivo index.html
