### ISSUE TITLE
Corrigir links do cabeçalho

### ISSUE THREAD

**Issue by agnogueira** [CMCuritiba/cmcuritiba.portalmodelo.theme#7]
Tem que ajustar os dois menus no cabeçalho:
Entre em contato - não responde nada
Portal da Transparência - não está com o link

**Comment by agnogueira** [comment]
@DePorto confirme para mim os links que devem aparecer nesses itens

**Comment by MarcioSilvaCMC2020** [comment]
Oi, @agnogueira, aqui é o Marcio. Certo, em relação ao Portal da Transparência, temos um problema. Existem 2 páginas, uma até 2016 e um sistema mais atual. Eu vou verificar se vamos manter as duas páginas, ou se uma será eliminada.

Já sobre o link Entre em contato, vou criar uma página interna no site com as informações gerais de contato com a CMC. Aí eu te passo o link da página por aqui?

**Comment by agnogueira** [comment]
@CamaraCuritiba ok, aguardando.
Assim que me passar os links coloco lá

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, para o Portal da Transparência, segue o link:

https://www.cmc.pr.gov.br/portaltransparencia/

A página que criei para o link Entre em contato é a seguinte:

https://pm3.cmc.pr.gov.br/institucional/fale-com-a-camara

**Comment by agnogueira** [comment]
links alterados
