### ISSUE TITLE
Refazer o rodapé

### ISSUE THREAD

**Issue by agnogueira** [CMCuritiba/cmcuritiba.portalmodelo.theme#8]
Tem o rodapé, que está em tabela, e o André disse que não vai funcionar assim. Ele perguntou se poderia resolver e eu já disse que sim, apesar de não saber como. Detalhe, está ativo no desktop, mas não no mobile. Aí eu não sei exatamento como vai resolver. Se ele mantiver essa padrão no desktop está bom. Agora, no mobile, tem que achar um modelo.

**Comment by MarcioSilvaCMC2020** [comment]
Conforme contato via Telegram com o @agnogueira, decidimos manter o rodapé como está no desktop e escondido no mobile. Porém será incluída uma seta do tipo voltar ao topo, como forma de solucionar a questão, que vai aparecer em qualquer forma de acesso. Faremos um teste e ajustes se for necessário. O código é o seguinte:

<script src="https://apps.elfsight.com/p/platform.js" defer></script>
<div class="elfsight-app-5bbce581-8991-42a7-85c4-f1823b97fda6"></div>

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 o script foi adicionado

**Comment by MarcioSilvaCMC2020** [comment]
Oi, @agnogueira. A ferramenta está funcionando de uma maneira geral, porém no item Notícia ela **não** funcionou. Até aparece o ícone, mas não executa a ação. Será possível ser corrigido? Ou, se não tiver jeito, não aparecer nas páginas de notícias.

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, esse problema foi corrigido no desktop. Porém, eu identifiquei que a seta de voltar ao topo aparece, mas não está funcionando, no mobile. Tem como corrigir isso?

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 corrigido. O problema é desse plugin, que sobrepoe seus dois widgets. Mas mesmo assim contorneio do nosso lado.

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, testei aqui e está funcionando. Show de bola.

**Comment by MarcioSilvaCMC2020** [comment]
@agnogueira, por algum motivo o botão de voltar ao topo parou de funcionar na versão mobile. Nem nas notícias, nem nas demais estruturas está funcionando. Por que será? No desktop está funcionando tudo normal? Obrigado.

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 Para mim funcionou aqui normalmente.
Pelo que vi esses problemas são do widgets que estamos usando. o widget de redes socias fica sobreposto ao widget de voltar ao topo. Nenhuma configuração lá que impeça isso?

**Comment by MarcioSilvaCMC2020** [comment]
OI, @agnogueira. Testei aqui e está funcionando normal também. Eu havia identificado o problema no sábado passado. Estranho, vou monitorar. Isso não havia acontecido. Sobre a configuração, eu desconheço, porém caso a situação persista posso entrar em contato com o suporte da empresa. Bom, por ora vou monitorar. Obrigado.
