### ISSUE TITLE
Ajustes no menu responsivo

### ISSUE THREAD

**Issue by agnogueira** [CMCuritiba/cmcuritiba.portalmodelo.theme#9]
Tem também aquela questão dos menus "sanduíche". Se para o mobile não poderia seguir o modelo do menu da Câmara dos Deputados, por exemplo. Para não ficar tão longa a lista, nem quebrar a rolagem horizontal - como ocorre hoje.

**Comment by MarcioSilvaCMC2020** [comment]
Então, @agnogueira, aqui está o tópico certo sobre isso, me perdoe pela confusão.

Copiando e colando:

Essa questão dos menus que é citado o site do Senado, me parece que está misturado aqui neste tópico. Vou conferir na lista geral e depois confirmo. Seria sobre o menu no mobile exibir de forma diferente do que está hj, que abre uma lista muito grande e a ideia seria abrir somente os menus principais, sem os submenus aparecendo. Confere aqui: https://www12.senado.leg.br/hpsenado

Olhando aqui, tem tbm a solução do portal da Câmara dos Deputados. As duas são opções que podemos seguir.

**Comment by agnogueira** [comment]
O site de vocês tem uma característica diferente do deles: os itens do primeiro nível são clicáveis.
No caso deles o usuário não clica no primeiro item (O institucional por exemplo, no de vocÊs e clicável, no deles não)

Por isso que é necessário que os menus estejam abeertos

**Comment by MarcioSilvaCMC2020** [comment]
Certo, @agnogueira. Mas é possível alguma mudança apenas para o mobile? Sim, os nossos menus são clicáveis, mas eles levam para uma página com um menu daquela seção. Portanto, se ficar somente os menus principais no mobile, não tem problema, pq a pessoa vai clicar e vai abrir em um novo menu com as opções que ela deseja buscar. Caso contrário, no mobile, a pessoa clica no menu e fica uma lista muito extensa para ela acessar aquele conteúdo. Tem alguma opção?

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 Não, o comportamento (se vai ter link ou não) precisa ser global, funcionar igual nos dois.

**Comment by agnogueira** [comment]
@MarcioSilvaCMC2020 conforme solicitado, removi o segundo nível do menu mobile. Veja se era isso mesmo.

**Comment by MarcioSilvaCMC2020** [comment]
Isso mesmo, @agnogueira. Obrigado!
